#!/bin/bash

# i3lock blurred screen inspired by /u/patopop007 and the blog post
# http://plankenau.com/blog/post-10/gaussianlock

# Timings are on an Intel i7-2630QM @ 2.00GHz

# Dependencies:
# imagemagick
# i3lock
# scrot (optional but default)
main (){
    # give notification, if scrot is not installed
    if [[ $(which scrot) = "" ]]; then
        $(notify-send -i /home/anup/Dropbox/ubuntu_DIY/i3/blur/error.jpeg "Error" "Please install scrot to use blur config.\n
        Use: 
        (i) sudo apt-get install scrot")
        exit
    fi

    # image location after taking the scrnsht and merging it with naruto
	IMAGE=/tmp/i3lock.png

    # location of naruto image
    naruto_IMAGE=/home/anup/Dropbox/ubuntu_DIY/i3/blur/naruto.png

    # taking scrnshot
	SCREENSHOT="scrot $IMAGE" # 0.46s

	# Alternate screenshot method with imagemagick. NOTE: it is much slower
	# SCREENSHOT="import -window root $IMAGE" # 1.35s

	# Here are some imagemagick blur types
	# Uncomment one to use, if you have multiple, the last one will be used

	# All options are here: http://www.imagemagick.org/Usage/blur/#blur_args
	#BLURTYPE="0x5" # 7.52s
	BLURTYPE="0x2" # 4.39s
	#BLURTYPE="5x2" # 3.80s
	#BLURTYPE="2x8" # 2.90s
	#BLURTYPE="2x3" # 2.92s

	# Get the screenshot, add the blur, merge it with naruto image and lock the screen with it
	$SCREENSHOT
	convert $IMAGE -blur $BLURTYPE $IMAGE
	convert $IMAGE -gravity center $naruto_IMAGE -composite $IMAGE
	i3lock -i $IMAGE
	rm $IMAGE
}

main
