#! /bin/bash

# this script returns the current percentage of brightness. It takes the current brightness and calculate the percentage from there. 

main (){
    # give notification, if light is not installed
    if [[ $(which light) = "" ]]; then
        $(notify-send -i /home/anup/Dropbox/ubuntu_DIY/i3/blur/error.jpeg "Error" "Please install light to use brightness config.\n
        Use: 
        (i) sudo apt-get install light
        (ii) chmod +x /usr/bin/light")
        exit
    fi

    # increasing the light depending upon hte increase amount
    increase_amount=5

    # command to incrase the light
    light -A $increase_amount

    # calculating the original and the max brightness
    original_brightness="$(cat /sys/class/backlight/intel_backlight/brightness)"
    max_brightness="$(cat /sys/class/backlight/intel_backlight/max_brightness)"

    # calculating the brightness percentage
    percentage=$(($(($original_brightness*100)) / $max_brightness))
    id=1200

    # send notification
    dunstify -r ${id} "Brightness" -h int:value:"$percentage" -i /home/anup/Dropbox/ubuntu_DIY/dunst/icon/bulb.png
}

main
