#! /bin/bash

# this script returns the current percentage of brightness. It takes the current brightness and calculate the percentage from there. 

main (){
    original_brightness="$(cat /sys/class/backlight/intel_backlight/brightness)"
    max_brightness="$(cat /sys/class/backlight/intel_backlight/max_brightness)"

    percentage=$(($(($original_brightness*100)) / $max_brightness))
    echo "brightness: $percentage%"
}


main
